### ISSUE TITLE
Which personShape is correct?

### ISSUE THREAD

**Issue by henrietteharmse** [ejp-rd-vp/CDE-semantic-model#100]
In [personShape.shex](https://github.com/ejp-rd-vp/CDE-semantic-model/blob/master/shex/sio-model/personShape.shex) it is defined as follows: 

```
:personShape IRI { 
  a [sio:SIO_000498] ;
  sio:SIO_000228 @:roleShape ;
  obo:RO_0002162 @:taxonShape 
}
```

In [patientStatusShape.shex](https://github.com/ejp-rd-vp/CDE-semantic-model/blob/master/shex/sio-model/patientStatusShape.shex) it is defined as:

```
:personShape IRI {
  a [sio:SIO_000498];
  sio:SIO_000228 @:personRoleShape;
  sio:SIO_000217 @:statusQualityShape
}
```

As far as I can see both use the same IRI, however the shape definitions are different. If we do need 2 different shapes for person I think we need 2 different IRIs.

**Comment by henrietteharmse** [comment]
@rajaram5 Do you have any thoughts on this?

**Comment by rajaram5** [comment]
Hi @henrietteharmse . The second shape is the correct one. One of the very first model is based on the `first shape` but later we decide to use `sio` as much as possible which resulted in `the second shape`. Thanks for reporting it. I will delete `the first shape` which is not valid anymore.

**Comment by henrietteharmse** [comment]
@rajaram5 Thanks for clarifying.
