### ISSUE TITLE
Not found of two IRIs used in the Figure

### ISSUE THREAD

**Issue by sxzhang1201** [ejp-rd-vp/CDE-semantic-model#11]
In the Pseudonym module:
The "rdc-meta:Pseudonym patient id" is not found, and "edam: Identifier" (http://edamontology.org/data_0842) is used instead.

In the Disease History and Diagnosis module:
The "omit:Antenatal" is not found, and "snomedct: antenatal" (http://purl.bioontology.org/ontology/SNOMEDCT/263675000) is used instead. 

The terms can be changed afterward when the missing IRIs is found and agreed upon.

**Comment by rajaram5** [comment]
These issues has been fixed in the new model
