### ISSUE TITLE
Unclear how to add multiple genetic diagnoses

### ISSUE THREAD

**Issue by martijnkersloot** [ejp-rd-vp/CDE-semantic-model#113]
It's currently unclear in the model how one should register multiple genetic diagnoses (https://github.com/ejp-rd-vp/CDE-semantic-model/blob/master/docs/genetic_diagnosis.md). 

When looking at the ShEx, it looks like that this is not modeled out (yet)?

**Comment by martijnkersloot** [comment]
Thanks for the fast reply! What do you mean with multiple lines? From which part of the model on? Role/Process/Output type/Attribute type?

**Comment by markwilkinson** [comment]
If you're using our templates and CSV transformation, it is one line of CSV per feature.

**Comment by martijnkersloot** [comment]
We're not using the templates / CSV transformation, but try to implement the model ourselves in our EDC system. I hope the model is independent from tooling? :)

**Comment by markwilkinson** [comment]
I see... then you can start from the process node and create multiple outputs that refer to the sequence variant ID that is an attribute of the patient (output nodes need to have distinct identifiers, but I believe everything else is constrained by its database URI identifier so you don't need to worry about uniqueness for those nodes).  Hope I got that right!  Our transformation just "does the right thing", so I haven't thought about it in a while ;-)

**Comment by markwilkinson** [comment]
Sorry!  No... multiple unique process nodes also... sorry, they carry (in principle) a timestamp and may have been determined at different times, so there has to be one process per output.  Sorry!!
