### ISSUE TITLE
make a clear map from option list for age of symptom and diagnosis to the set of CDEs

### ISSUE THREAD

**Issue by brunasv** [ejp-rd-vp/CDE-semantic-model#127]
In the model for [Date of Diagnosis](https://github.com/ejp-rd-vp/CDE-semantic-model/blob/master/docs/5.Date_of_diagnosis.md), the CDE option "At birth", is typed as postnatal, which reads broader than something you see immediately after or "at birth". 
Suggestion for "at birth":  [Postpartum](http://purl.obolibrary.org/obo/NCIT_C92851) which describes the precise moment after birth (there is also [Finding during childbirth labor](http://purl.obolibrary.org/obo/NCIT_C92718), although this one describes a finding and the CDEs seem to describe a period of time)

In the [Date of Symptoms](https://github.com/ejp-rd-vp/CDE-semantic-model/blob/master/docs/5.Date_of_symptom.md)  the options list offered in the model is broader than the CDEs one (which is good semantically but confusing for users trying to match the model with the set of CDEs). Suggestion: Offer these as a possibility (if so, make it clear in the glossary), but keep it close to the CDEs which only seem to care about prenatal/antenatal, at birth/postpartum, unknown/undetermined or a precise date. The clearer the better for the pre-set querying system, no?

**Comment by pabloalarconm** [comment]
Stages have been removed from the model, so its no longer a problem to be represented at those models
