### ISSUE TITLE
Alternative rdf model is proposed in module patient status

### ISSUE THREAD

**Issue by rajaram5** [ejp-rd-vp/CDE-semantic-model#16]
Alternative rdf model is proposed in `patient status` model. Model `dead date` as a `relationship`  of person. In the current model `dead date` is modelled as a separate instance.

Note: This issue is reported by @ronaldcornet via email

**Comment by rajaram5** [comment]
@ronaldcornet Please feel free to modify this issue in case if I misunderstood your comments

**Comment by ronaldcornet** [comment]
What I meant to state is:
birthdate is an attribute of Person. Similarly, deathdate should be an attribute of Person, not of Status.

**Comment by rajaram5** [comment]
This issue has been fixed in the new SIO model. Thanks for reporting
