### ISSUE TITLE
Question about diagnosis code model

### ISSUE THREAD

**Issue by rajaram5** [ejp-rd-vp/CDE-semantic-model#18]
Why `diagnosis code` is modelled as a property of a `diagnosis`? 

Note: This issue is reported by @ronaldcornet via email

**Comment by rajaram5** [comment]
@ronaldcornet Please feel free to modify this issue in case if I misunderstood your comments

**Comment by ronaldcornet** [comment]
Diagnosis_code seems an unnecessary indirection.
Suppose person P has diabetes
P has-condition X 
X a snomed:diabetes
 
And then maybe: (diagnosis as a role is another discussion)
X ro:has-role D
D a sio:Diagnosis
D /determined-by/ DoctorX
D /determined-at/ May 23rd
...

**Comment by rajaram5** [comment]
This issue has been addressed in the new SIO model. In the new model the diagnosis code is attached as an attribute to the diagnosis
