### ISSUE TITLE
Correct ontological term for Pseudonym

### ISSUE THREAD

**Issue by brunasv** [ejp-rd-vp/CDE-semantic-model#36]
On the [diagram from the wiki page for pseudonym module](https://github.com/ejp-rd-vp/ERN-common-data-elements/wiki/Pseudonym), pseudonym is annotated as [rdc-meta, which is unresolvable](https://rdf.biosemantics.org/ontologies/rd-connect/23d2f73b_6bb4_4c8f_af98_a3bb4a1f8e30), but means pseudonym. The shex file for this module updates to [edam](http://edamontology.org/data_0842) which resolves to _identifier_ and not specifically to _pseudonym_. 
```PREFIX : <http://purl.org/ejp-rd/cde/v010/shex/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX edam: <http://edamontology.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>


:personShape IRI {
  a [obo:NCBITaxon_9606]
}

:identifierShape IRI {
  a [edam:data_0842];
  dct:identifier xsd:string;
  obo:IAO_0000219 @:personShape
}
```

**Comment by rajaram5** [comment]
thanks for reporting this issue has been fixed in the new model
