### ISSUE TITLE
check sio:measurement value definition 

### ISSUE THREAD

**Issue by rajaram5** [ejp-rd-vp/CDE-semantic-model#40]
`sio:measurement value` predicate definition forces us to use `numeric value` as an object. @markwilkinson  agreed to follow up this issue with sio ontology developers.

**Comment by NuriaQueralt** [comment]
Hi @rajaram5 and @markwilkinson, IAO models measurement values as 'measurement data item' (is_a 'information content entity'), which is defined as a recording of the output of an assay. Examples of measurement data are the recoding of the weight of a mouse as {40,mass,"grams"}, the recording of an observation of the behavior of the mouse {,process,"agitated"}, the recording of the expression level of a gene as measured through the process of microarray experiment {3.4,luminosity,}. See IAO [tree](shorturl.at/ipqrR). 

On the other hand, reading about modelling phenotypic descriptions in ontologies using the Quality-Entity description [1], I come across an interesting design used in PATO that may be of help in this issue: 'PATO is divided at the top level between qualities of biological objects and qualities (physical quality) of processes (or temporal qualities).' see [PATO tree](shorturl.at/pBEJZ). Then, SIO could mint a new class like 'temporal or procedural quality' for measurable phenotypes and maybe refine the 'sio:object-quality' as 'physical object quality' for qualitative phenotypes?..

[1] https://doi.org/10.1186/gb-2010-11-1-r2

**Comment by rajaram5** [comment]
this issue has been fixed in the new model
