### ISSUE TITLE
Change wording (decide on) of Sex / Gender

### ISSUE THREAD

**Issue by martijnkersloot** [ejp-rd-vp/CDE-semantic-model#46]
In the [Personal information module](https://github.com/ejp-rd-vp/CDE-semantic-model/wiki/Personal-information) sex and gender are both used, but they cannot be used interchangeably. 

- Gender = a psychological concept (how you identify yourself)
- Sex = an anatomical concept (what gender characteristics were you born with)

Since the Common Data Elements are using 'Sex', I think we should switch to that.

**Comment by rajaram5** [comment]
This issue has been fixed in the new SIO model
