### ISSUE TITLE
Replace "efo:age at diagnosis" with "snomedct:age at diagnosis"?

### ISSUE THREAD

**Issue by sxzhang1201** [ejp-rd-vp/CDE-semantic-model#6]
The definition citation of "efo: age at diagnosis" (see [http://www.ebi.ac.uk/efo/EFO_0004918](url)) in the module **_Disease History and Diagnosis_** is "snomedct: age at diagnosis" (see [http://purl.bioontology.org/ontology/SNOMEDCT/423493009](url)). 

So it may be better to directly use the SNOMED CT term to reduce the ontology used.

**Comment by rajaram5** [comment]
Not relevant anymore due to use of SIO based model
