### ISSUE TITLE
Personal Information (0.1.0) date formats changes are not clear

### ISSUE THREAD

**Issue by brunasv** [ejp-rd-vp/CDE-semantic-model#65]
mm-dd changed to mm-dd-yyyy, whilst in the end, we describe yyyy-mm-dd. Confusing for the user to know which format of date to represent in the database. In addition, CDEs says dd-mm-yyyy.

**Comment by brunasv** [comment]
https://github.com/ejp-rd-vp/CDE-semantic-model/wiki/Personal-information

**Comment by nirupamaBenis** [comment]
use xsd:date in model
