### ISSUE TITLE
Misuse of Data Property "sio:has_value"?

### ISSUE THREAD

**Issue by sxzhang1201** [ejp-rd-vp/CDE-semantic-model#7]
The property "sio:has_value"(see [https://raw.githubusercontent.com/micheldumontier/semanticscience/master/ontology/sio/release/sio-release.owl#](url)) is the datatype property whose range should be literal (see [https://www.w3.org/TR/rdf11-concepts/#section-Graph-Literal](url)) instead of IRI. So the `sio:has_value` in the following RDF triples are not properly used:

**Personal Information Module:**
gender ->` sio:has_value` -> SNOMECT:Gender_Unknown (for example)

**Patient Status Module:**
status ->`sio:has_value` -> pato:alive (for example)

**Disease History and Diagnosis Module:**
diagnosis_age -> `sio:has_value` -> diagnosis_age_value 
symptom_age -> `sio:has_value` -> symptom_age_value

**Consent Module:**
consent_contact ->  `sio:has_value` -> ncit:Yes (for example)
consent_reuse->  `sio:has_value` -> ncit:Yes (for example)

**Comment by rajaram5** [comment]
Thanks for reporting this bug has been fixed in the newer SIO model
